[theme]
primaryColor = "#238DFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#020202"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false